name: ssi
packages:
  - .
  - example/dids/didwebvh
scripts:
  fix:
    exec: dart fix --apply
    concurrency: 4
    failFast: true
    noSelect: true
    packageFilters:
      includePrivatePackages: false
      diff: origin/main
  analyze:
    exec: dart analyze .
    concurrency: 4
    failFast: true
    noSelect: true
    packageFilters:
      includePrivatePackages: false
      diff: origin/main
  test:
    run: |
      melos run test-dart
  test-dart:
    description: Run tests in each dart package
    exec: dart run coverage:test_with_coverage
    dirExists: test
    concurrency: 4
    failFast: true
    noSelect: true
    packageFilters:
      private: false
      diff: origin/main
      ignore:
        - "*_example*"
