name: affinidi_ssi

packages:
  - "./"
  - packages/**

ignore:
  - packages/sdjwt_sdk/example

scripts:
  test:
    name: test
    description: "test with coverage"
    exec: dart run coverage:test_with_coverage
   