name: ssi
description: Affinidi SSI library
version: 1.0.0-dev.19
repository: https://github.com/affinidi/affinidi-ssi-dart
environment:
  sdk: ^3.6.0
dependencies:
  base_codecs: ^1.0.1
  bip32: ^2.0.0
  cryptography: ^2.7.0
  ecdsa: ^0.1.2
  ed25519_edwards: ^0.3.1
  ed25519_hd_key: ^2.2.0
  http: ^1.1.0
  elliptic: ^0.3.11
  jose_plus: ^0.4.6
  json_ld_processor: ^1.0.4
  pointycastle: ^3.9.1
  selective_disclosure_jwt: ^1.0.0
  x25519: ^0.1.1
  web3dart: ^2.7.3
  crypto_keys: ^0.3.0+1
  dart_multihash: ^1.0.1
  uuid: ^4.5.1
  crypto: ^3.0.6

  dart_ssi:
    path: /Users/sebastian.m/workspace/affinidi/didcomm/dart-sdk

dev_dependencies:
  coverage: ^1.11.1
  lints: ^5.0.0
  # dart_flutter_team_lints: ^3.2.1
  melos: ^6.3.2
  test: ^1.24.0
  jwt_decoder: ^2.0.1
  aws_kms_api: ^2.0.0
  aws_signature_v4: ^0.6.4
  shared_aws_api: ^2.0.2
publish_to: none

dependency_overrides:
  dart_ssi:
    path: /Users/sebastian.m/workspace/affinidi/didcomm/dart-sdk
