name: affinidi_ssi
description: Affinidi SSI library
version: 1.0.0-dev.3
repository: https://github.com/affinidi/affinidi-ssi-dart

environment:
  sdk: ^3.6.1


dependencies:
  pointycastle: ^3.9.1
  bip32: ^2.0.0
  base_codecs: ^1.0.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
