name: ssi
description: >-
  Affinidi SSI library for Dart provides a comprehensive suite of tools and
  libraries for implementing Self-Sovereign Identity (SSI) solutions.
version: 2.11.3
repository: https://github.com/affinidi/affinidi-ssi-dart
environment:
  sdk: ^3.6.0
dependencies:
  archive: ^4.0.7
  base_codecs: ^1.0.1
  bip32_plus: ^1.0.0
  crypto: ^3.0.3
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^3.2.0
  ecdsa: ^0.1.2
  ed25519_edwards: ^0.3.1
  ed25519_hd_key: ^2.3.0
  elliptic: ^0.3.11
  flutter_curl: 0.5.0
  flutter_downloader: 1.11.0
  http: ^1.4.0
  json_ld_processor: ^1.0.4
  meta: ^1.15.0
  pointycastle: ^4.0.0
  selective_disclosure_jwt: ^1.1.0
  x25519: ^0.1.1

dev_dependencies:
  aws_kms_api: ^2.0.0
  aws_signature_v4: ^0.6.4
  coverage: ^1.11.1
  dart_flutter_team_lints: ^3.2.1
  melos: ^6.3.2
  shared_aws_api: ^2.0.2
  test: ^1.24.0

topics:
  - ssi
  - cryptography
  - did

command:
  version:
    changelogCommitBodies:
      include: true
      onlyBreaking: false
