/// An abstract class representing a generic generator that produces values of
/// type [T]. The class defines a contract for implementing custom generators,
/// ensuring that all subclasses provide a `generate()` method.
///
/// - [T]: The type of value generated by the generator class.
///
/// @internal
/// This is an internal implementation detail, not intended for direct use by consumers of the package.
///
/// Example:
/// ```dart
/// class RandomNumberGenerator extends Generator<int> {
///   @override
///   int generate() {
///     return Random().nextInt(100);
///   }
/// }
///
/// void main() {
///   final generator = RandomNumberGenerator();
/// }
/// ```
abstract class Generator<T> {
  /// Generates and returns a value of type [T].
  T generate();
}
