// ignore_for_file: avoid_print

import 'dart:convert';

import 'package:ssi/src/credentials/jwt/jwt_dm_v1_suite.dart';
import 'package:ssi/ssi.dart';

void main() {
  // Parse the JWT VC
  final parsedJwtVc = UniversalParser.parse(jwtVcString);

  // Access the credential data (as JwtVcDataModelV1)
  if (parsedJwtVc is JwtVcDataModelV1) {
    print(
        'Parsed JWT VC Payload (vc field):\n${jsonEncode(parsedJwtVc.toJson())}');
    print('\nComplete JWS Payload:\n${jsonEncode(parsedJwtVc.jws.payload)}');
    print('\nSerialized JWT:\n${parsedJwtVc.serialized}');
  } else {
    print('Failed to parse as JWT VC V1.');
  }
}

// Example JWT VC string (replace with a valid JWT VC generated by issuance.dart)
const jwtVcString =
    'eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6a2V5Ono2TWtrZFRQWFFWSlNwcUxkd0V0UHVQeVhYRjU4amN0M1BSSGJWZzY5WThzZHRYMSN6Nk1ra2RUUFhRVkpTcHFMZHdFdFB1UHlYVEY1OGpjdDNQUkhiVmc2OVk4c2R0WDEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3MzIwMjYzMDYsIm5iZiI6MTcxNjQ3NDMwNiwiaXNzIjoiZGlkOmtleTp6Nk1ra2RUUFhRVkpTcHFMZHdFdFB1UHlYVEY1OGpjdDNQUkhiVmc2OVk4c2R0WDEiLCJqdGkiOiJ1dWlkOjEyMzQ1NmFiY2QiLCJzdWIiOiJkaWQ6ZXhhbXBsZTpob2xkZXIxMjMiLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vc2NoZW1hLmFmZmluaWRpLmNvbS9Vc2VyUHJvZmlsZVYxLTAuanNvbmxkIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVc2VyUHJvZmlsZSJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDpleGFtcGxlOmhvbGRlcjEyMyIsIkZuYW1lIjoiRm5hbWUiLCJMYW1lIjoiTGFtZSIsIkFnZSI6IjIyIiwiQWRkcmVzcyI6IkVpaGhvcm5zdHIifX19.X2w4bHc0eFZyTzNlWlB1MktFdVh3c1dWVmdhR3l6VnB6T2p5bWd0Z3l1RnlxWjh0NzZ3YjZlZ3ZlZ294NGl1Z0Zk' // Replace with actual JWT
    ;
