// ignore_for_file: avoid_print

import 'package:ssi/ssi.dart';

void main() async {
  // Parse the JWT VC
  final parsedJwtVc = UniversalParser.parse(jwtVcString);

  if (parsedJwtVc is JwtVcDataModelV1) {
    // 1. Verify Integrity (Signature)
    final integrityVerifier = VcIntegrityVerifier();
    final integrityResult = await integrityVerifier.verify(parsedJwtVc);
    print('Integrity verification result: ${integrityResult.isValid}');
    if (!integrityResult.isValid) {
      print('  Errors: ${integrityResult.errors}');
    }

    // 2. Verify Expiry (using 'exp' and 'nbf' claims in JWT payload)
    final expiryVerifier = VcExpiryVerifier();
    final expiryResult = await expiryVerifier.verify(parsedJwtVc);
    print('Expiry verification result: ${expiryResult.isValid}');
    if (!expiryResult.isValid) {
      print('  Errors: ${expiryResult.errors}');
    }

    // Combined result
    final overallValid = integrityResult.isValid && expiryResult.isValid;
    print('\nOverall JWT VC valid: $overallValid');
  } else {
    print('Failed to parse as JWT VC V1.');
  }
}

// Example JWT VC string (replace with a valid JWT VC generated by issuance.dart)
const jwtVcString =
    'eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6a2V5OnpRM3NoWDZtd0pBRGJ0OUx3S2hjbXZaOUJrcWpKaXlOTjRWUGs4amRIOTVRWDJZbjUjelEzc2hYNm13SkFEYnQ5THdLaGNtdlo5QmtxakppeU5ONFZQazhqZEg5NVFYMlluNSIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NjU1NDc0NTQsImlzcyI6eyJpZCI6ImRpZDprZXk6elEzc2hYNm13SkFEYnQ5THdLaGNtdlo5QmtxakppeU5ONFZQazhqZEg5NVFYMlluNSJ9LCJqdGkiOiJ1dWlkOjEyMzQ1NmFiY2QiLCJzdWIiOiJkaWQ6ZXhhbXBsZTpob2xkZXIxMjMiLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vc2NoZW1hLmFmZmluaWRpLmNvbS9Vc2VyUHJvZmlsZVYxLTAuanNvbmxkIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVc2VyUHJvZmlsZSJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDpleGFtcGxlOmhvbGRlcjEyMyIsIkZuYW1lIjoiRm5hbWUiLCJMbmFtZSI6IkxhbWUiLCJBZ2UiOiIyMiIsIkFkZHJlc3MiOiJFaWhob3Juc3RyIn19fQ.0Np3F1I0jZi5ynNnBf4TIVxzUHWpxBI7oL008AHPODwk4s4ZfoqbnuGi9Jb2RimK4ZZ5lKmllvhQEFFJLMD2bw';
