// ignore_for_file: avoid_print

import 'package:ssi/src/credentials/jwt/jwt_dm_v1_suite.dart';
import 'package:ssi/src/credentials/verification/vc_expiry_verifier.dart';
import 'package:ssi/src/credentials/verification/vc_integrity_verifier.dart';
import 'package:ssi/ssi.dart';

void main() async {
  // Parse the JWT VC
  final parsedJwtVc = UniversalParser.parse(jwtVcString);

  if (parsedJwtVc is JwtVcDataModelV1) {
    // 1. Verify Integrity (Signature)
    final integrityVerifier = VcIntegrityVerifier();
    final integrityResult = await integrityVerifier.verify(parsedJwtVc);
    print('Integrity verification result: ${integrityResult.isValid}');
    if (!integrityResult.isValid) {
      print('  Errors: ${integrityResult.errors}');
    }

    // 2. Verify Expiry (using 'exp' and 'nbf' claims in JWT payload)
    final expiryVerifier = VcExpiryVerifier();
    final expiryResult = await expiryVerifier.verify(parsedJwtVc);
    print('Expiry verification result: ${expiryResult.isValid}');
    if (!expiryResult.isValid) {
      print('  Errors: ${expiryResult.errors}');
    }

    // Combined result
    final overallValid = integrityResult.isValid && expiryResult.isValid;
    print('\nOverall JWT VC valid: $overallValid');
  } else {
    print('Failed to parse as JWT VC V1.');
  }
}

// Example JWT VC string (replace with a valid JWT VC generated by issuance.dart)
const jwtVcString =
    'eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6a2V5Ono2TWtrZFRQWFFWSlNwcUxkd0V0UHVQeVhYRjU4amN0M1BSSGJWZzY5WThzZHRYMSN6Nk1ra2RUUFhRVkpTcHFMZHdFdFB1UHlYVEY1OGpjdDNQUkhiVmc2OVk4c2R0WDEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3MzIwMjYzMDYsIm5iZiI6MTcxNjQ3NDMwNiwiaXNzIjoiZGlkOmtleTp6Nk1ra2RUUFhRVkpTcHFMZHdFdFB1UHlYVEY1OGpjdDNQUkhiVmc2OVk4c2R0WDEiLCJqdGkiOiJ1dWlkOjEyMzQ1NmFiY2QiLCJzdWIiOiJkaWQ6ZXhhbXBsZTpob2xkZXIxMjMiLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vc2NoZW1hLmFmZmluaWRpLmNvbS9Vc2VyUHJvZmlsZVYxLTAuanNvbmxkIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVc2VyUHJvZmlsZSJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDpleGFtcGxlOmhvbGRlcjEyMyIsIkZuYW1lIjoiRm5hbWUiLCJMYW1lIjoiTGFtZSIsIkFnZSI6IjIyIiwiQWRkcmVzcyI6IkVpaGhvcm5zdHIifX19.X2w4bHc0eFZyTzNlWlB1MktFdVh3c1dWVmdhR3l6VnB6T2p5bWd0Z3l1RnlxWjh0NzZ3YjZlZ3ZlZ294NGl1Z0Zk' // Replace with actual JWT
    ;
