name: kms_wallet
description: Example of Affinidi SSI wallet initialized with AWS KMS
version: 1.0.0-dev.1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  ssi:
    path: ../../
  aws_kms_api: ^2.0.0
  aws_signature_v4: ^0.6.4
  shared_aws_api: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
