name: sdjwt_sdk
version: 1.0.0
description: A Dart SDK for working with Selective Disclosure JSON Web Tokens (SD-JWT) following the SD-JWT specification.
repository: https://github.com/affinidi/affinidi-ssi-dart/tree/main/packages/sdjwt_sdk
issue_tracker: https://github.com/affinidi/affinidi-ssi-dart/issues

topics:
  - jwt
  - sd-jwt
  - selective-disclosure
  - cryptography
  - authentication
  - did

environment:
  sdk: ^3.6.0

dependencies:
  convert: ^3.1.2
  crypto: ^3.0.6
  jose_plus: ^0.4.6
  path: ^1.9.1
  uuid: ^4.5.1
  equatable: ^2.0.7
  crypto_keys_plus: ^0.4.0
  rfc_6901: ^0.2.0
  meta: ^1.16.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mocktail: ^1.0.4

platforms:
  android:
  ios:
  web:
