name: publish
   
on:
  push:
    tags:
      - '**v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    environment: release
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
      - uses: bluefireteam/melos-action@v3
        with:
          publish: false