name: release
on:
  push:
    branches:
      - test/dart-security-scanner-reports
jobs:
  dart-pipeline:
    uses: affinidi/pipeline-dart/.github/workflows/release.yaml@test/dart-security-scanner-reports
    secrets: inherit
